In [4]:
#Array

import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
#2D Array

arr2 = np.array([[10,20,30],
                 [40,50,60],
                 [70,80,90]
                ])
print(arr2)
print(arr2.shape)  # Row & Columns
print(arr2.ndim)   # Number of Dimensions
print(arr2.dtype)  # Data type of elements

[[10 20 30]
 [40 50 60]
 [70 80 90]]
(3, 3)
2
int32


In [20]:
#2D Array Shortcuts

zeros_arr = np.zeros((3,3))
ones_arr = np.ones((3,3))
full_arr = np.full((3,3),128)
identy = np.eye(3)
range_arr = np.arange(0,10,2)
lin_arr = np.linspace(0,255,2)

print(zeros_arr)
print()
print(ones_arr)
print()
print(full_arr)
print()
print(identy)
print()
print(range_arr)
print()
print(lin_arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[128 128 128]
 [128 128 128]
 [128 128 128]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[0 2 4 6 8]

[  0. 255.]


In [23]:
#Index and Slicing
img_like = np.array([[10, 20, 30, 40],
                     [50, 60, 70, 80],
                     [90, 100,110,120],
                     [130,140,150,160]])

print(img_like[0, 0])      # row 0, column 0
print(img_like[1, 2])      # row 1, column 2
print(img_like[0, :])      # entire first row
print(img_like[:, 0])      # entire first column
print(img_like[1:3, 1:3])  # a sub-block

10
70
[10 20 30 40]
[ 10  50  90 130]
[[ 60  70]
 [100 110]]


In [7]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[10, 20], [30, 40]])

print(a + b)
print()
print(a * b)
print()
print(a @ b)
print()
print(a + 5)
print()
print(a * 2)

[[11 22]
 [33 44]]

[[ 10  40]
 [ 90 160]]

[[ 70 100]
 [150 220]]

[[6 7]
 [8 9]]

[[2 4]
 [6 8]]


In [9]:
data = np.array([12, 45, 7, 89, 34, 100])

print(data.max())
print(data.min())
print(data.mean())
print(data.sum())
print(np.clip(data, 20, 80))    # Clip values below 20, above 80

100
7
47.833333333333336
287
[20 45 20 80 34 80]
